### ISSUE TITLE
Rename SSP2Ariadne to SSP2EU

### ISSUE THREAD

**Issue by johanneskoch94** [pik-piam/mrcommons#24]
As decided in the REMIND meeting we need to rename "SSP2Ariadne" to "SSP2EU". This will probably require updating multiple packages at the same time. I will take care of mrcommons and mrremind. @Loisel will you take care of the edge packages? Thing is, I'm on vacation next week, so I'll probably only get to it the week after. Just wanted to give you a heads up :)

**Comment by Loisel** [comment]
yes, I can take care of EDGE-T.

**Comment by johanneskoch94** [comment]
Done in 11e7f4f39b207b05e99501a1bc583ed5e2e5e947 and package mrdrivers
