### ISSUE TITLE
issue in convertJames2019

### ISSUE THREAD

**Issue by johanneskoch94** [pik-piam/mrcommons#8]
Hi David, 
`readSource("James2019", subtype="IHME_USD05_PPP_pc")` returns a magpie object, with the dimension name "Year" missing. Instead the time dimension is called "X". This produces an error down the line in `calcOutput("Capital")` (run as part of remind-input-preparation). Is this something you could fix? Or was this on purpose (in line with the new magclass changes perhaps?), and we should fix `calcOuptut("Capital")` ?
Thank you!!

**Comment by caviddhen** [comment]
Hey Johannes! 

The set name "Year" should be there now. Thanks for flagging this!

**Comment by johanneskoch94** [comment]
Awsome, thx for the super quick fix!
